export const SET_TOTAL_TREES = 'SET_TOTAL_TREES'
export const SET_UPDATE_TIMER = 'SET_UPDATE_TIMER'
export const SET_TOP_DONERS = 'SET_TOP_DONERS'
export const SET_LATEST_DONERS = 'SET_LATEST_DONERS'
