export const SET_TOTAL_TREES = 'SET_TOTAL_TREES'
export const SET_UPDATE_TIMER = 'SET_UPDATE_TIMER'
export const SET_TOP_DONERS = 'SET_TOP_DONERS'
export const SET_LATEST_DONERS = 'SET_LATEST_DONERS'


// lOGIN ACTIONS
export const SET_EMAIL = 'SET_EMAIL'
export const SET_USER_NAME = 'SET_USER_NAME'
export const SET_PASSWORD = 'SET_PASSWORD'
export const SET_PHONE_NUMBER = 'SET_PHONE_NUMBER'
export const SET_CONFIRMATION_CODE = 'SET_CONFIRMATION_CODE'
export const SET_USER_TOKEN = 'SET_USER_TOKEN'
